/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdErrorBoundary: typeof import('./components/ads/AdErrorBoundary.vue')['default']
    AdNoticeDialog: typeof import('./components/ads/AdNoticeDialog.vue')['default']
    AdSlotView: typeof import('./components/ads/AdSlotView.vue')['default']
    BootGate: typeof import('./components/boot/BootGate.vue')['default']
    ExamCalculator: typeof import('./components/exam/ExamCalculator.vue')['default']
    InstallPrompt: typeof import('./components/pwa/InstallPrompt.vue')['default']
    PracticeConfigSheet: typeof import('./components/practice/PracticeConfigSheet.vue')['default']
    ResultCardAd: typeof import('./components/ads/ResultCardAd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleConfigPanel: typeof import('./components/practice/RuleConfigPanel.vue')['default']
    SplashAd: typeof import('./components/ads/SplashAd.vue')['default']
    UpdatePrompt: typeof import('./components/pwa/UpdatePrompt.vue')['default']
  }
}
